DROP TABLE Genero CASCADE CONSTRAINTS;
DROP TABLE MiembroCrew CASCADE CONSTRAINTS;
DROP TABLE MiembroCast CASCADE CONSTRAINTS;
DROP TABLE Pelicula CASCADE CONSTRAINTS;
DROP TABLE Fecha CASCADE CONSTRAINTS;
DROP TABLE Crew CASCADE CONSTRAINTS;
DROP TABLE Voto CASCADE CONSTRAINTS;
DROP TABLE Cast CASCADE CONSTRAINTS;